# Generated by Django 5.2.4 on 2025-07-26 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['position'], 'verbose_name': 'Объект меню', 'verbose_name_plural': 'Объекты меню'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_app.menuitem', verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя'),
        ),
    ]
